name: Cloudbase CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_run:
    workflows: [ "Uptime CI" ]
    types: [ completed ]
jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-latest
    timeout-minutes: 7
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - uses: peaceiris/actions-gh-pages@v3.8.0
        name: GitHub Pages Deploy
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: "site/status-page/__sapper__/export/"
          user_name: "Upptime Bot"
          user_email: "73812536+upptime-bot@users.noreply.github.com"

      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{ secrets.TENCENTCLOUD_CLOUDBASE_SECRET_ID }}
          secretKey: ${{ secrets.TENCENTCLOUD_CLOUDBASE_SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
